openapi: 3.0.1
info:
  title: Parts Inventory API
  version: '1.0'
paths:
  /add:
    post:
      summary: Add part to user Google Sheet
      operationId: addToSheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sheet_id
                - part_name
                - quantity
              properties:
                sheet_id:
                  type: string
                part_name:
                  type: string
                quantity:
                  type: integer
                image_url:
                  type: string
      responses:
        '200':
          description: Success
        '400':
          description: Invalid input
        '500':
          description: Server error
servers:
  - url: https://diy-buildfrombox-googlesheets.onrender.com
